import { University } from '@/types';

export const UNIVERSITIES: University[] = [
  {
    id: 'furb',
    name: 'FURB - Universidade Regional de Blumenau',
    courses: [
      'Administração',
      'Arquitetura e Urbanismo',
      'Ciência da Computação',
      'Ciências Contábeis',
      'Direito',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia de Produção',
      'Engenharia Elétrica',
      'Medicina',
      'Psicologia',
      'Sistemas de Informação',
    ],
  },
  {
    id: 'udesc',
    name: 'UDESC - Universidade do Estado de Santa Catarina',
    courses: [
      'Administração',
      'Ciências Biológicas',
      'Design',
      'Educação Física',
      'Enfermagem',
      'Engenharia Mecânica',
      'Engenharia de Software',
      'Fisioterapia',
      'História',
      'Medicina Veterinária',
      'Pedagogia',
      'Química',
    ],
  },
  {
    id: 'unisul',
    name: 'UNISUL - Universidade do Sul de Santa Catarina',
    courses: [
      'Administração',
      'Arquitetura e Urbanismo',
      'Biomedicina',
      'Ciências Contábeis',
      'Design Gráfico',
      'Direito',
      'Educação Física',
      'Engenharia Civil',
      'Jornalismo',
      'Nutrição',
      'Psicologia',
      'Publicidade e Propaganda',
    ],
  },
  {
    id: 'univali',
    name: 'UNIVALI - Universidade do Vale do Itajaí',
    courses: [
      'Administração',
      'Ciência da Computação',
      'Ciências Contábeis',
      'Direito',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia de Produção',
      'Farmácia',
      'Fisioterapia',
      'Medicina',
      'Odontologia',
      'Psicologia',
    ],
  },
  {
    id: 'unochapeco',
    name: 'UNOCHAPECÓ - Universidade Comunitária da Região de Chapecó',
    courses: [
      'Administração',
      'Agronomia',
      'Ciências Contábeis',
      'Direito',
      'Educação Física',
      'Enfermagem',
      'Engenharia Civil',
      'Fisioterapia',
      'Medicina',
      'Nutrição',
      'Pedagogia',
      'Psicologia',
    ],
  },
  {
    id: 'unoesc',
    name: 'UNOESC - Universidade do Oeste de Santa Catarina',
    courses: [
      'Administração',
      'Arquitetura e Urbanismo',
      'Ciências Contábeis',
      'Direito',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia Mecânica',
      'Farmácia',
      'Fisioterapia',
      'Medicina',
      'Odontologia',
      'Pedagogia',
    ],
  },
];
