import { University } from '@/types';

export const UNIVERSITIES: University[] = [
  {
    id: 'univali',
    name: 'UNIVALI - Universidade do Vale do Itajaí',
    courses: [
      'Administração',
      'Artes Visuais',
      'Biomedicina',
      'Ciência da Computação',
      'Ciências Biológicas',
      'Ciências Contábeis',
      'Comércio Exterior',
      'Construção Naval',
      'Design',
      'Direito',
      'Educação Especial',
      'Educação Física - Bacharelado',
      'Educação Física - Licenciatura',
      'Enfermagem',
      'Engenharia Ambiental e Sanitária',
      'Engenharia Civil',
      'Engenharia de Computação',
      'Engenharia de Produção',
      'Engenharia Elétrica',
      'Engenharia Mecânica',
      'Farmácia',
      'Fisioterapia',
      'Fonoaudiologia',
      'Fotografia',
      'Gastronomia',
      'História',
      'Inteligência Artificial',
      'Jornalismo',
      'Letras',
      'Matemática',
      'Medicina',
      'Música',
      'Nutrição',
      'Oceanografia',
      'Odontologia',
      'Pedagogia',
      'Produção Audiovisual',
      'Psicologia',
      'Publicidade e Propaganda',
      'Relações Internacionais',
      'Relações Públicas',
      'Sistemas para Internet',
      'Terapia Ocupacional',
    ],
  },
  {
    id: 'furb',
    name: 'FURB - Universidade Regional de Blumenau',
    courses: [
      'Administração',
      'Arquitetura e Urbanismo',
      'Artes Visuais',
      'Biomedicina',
      'Ciência da Computação',
      'Ciência de Dados',
      'Ciências Biológicas',
      'Ciências Contábeis',
      'Ciências Econômicas',
      'Ciências Sociais',
      'Comércio Exterior',
      'Dança',
      'Design',
      'Direito',
      'Educação Física - Bacharelado',
      'Educação Física - Licenciatura',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia de Alimentos',
      'Engenharia de Produção',
      'Engenharia de Telecomunicações',
      'Engenharia Elétrica',
      'Engenharia Florestal',
      'Engenharia Mecânica',
      'Engenharia Química',
      'Farmácia',
      'Física',
      'Fisioterapia',
      'História',
      'Jornalismo',
      'Letras - Português',
      'Letras - Inglês',
      'Matemática',
      'Medicina',
      'Medicina Veterinária',
      'Música',
      'Nutrição',
      'Odontologia',
      'Pedagogia',
      'Psicologia',
      'Publicidade e Propaganda',
      'Química',
      'Sistemas de Informação',
    ],
  },
  {
    id: 'unesc',
    name: 'UNESC - Universidade do Extremo Sul Catarinense',
    courses: [
      'Administração',
      'Arquitetura e Urbanismo',
      'Biomedicina',
      'Ciências Biológicas',
      'Ciências Contábeis',
      'Direito',
      'Educação Física',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia Mecânica',
      'Farmácia',
      'Fisioterapia',
      'Fonoaudiologia',
      'Medicina',
      'Medicina Veterinária',
      'Nutrição',
      'Odontologia',
      'Pedagogia',
      'Psicologia',
      'Serviço Social',
      'Sistemas de Informação',
      'Terapia Ocupacional',
    ],
  },
  {
    id: 'unoesc',
    name: 'UNOESC - Universidade do Oeste de Santa Catarina',
    courses: [
      'Administração',
      'Agronomia',
      'Arquitetura e Urbanismo',
      'Biomedicina',
      'Ciência da Computação',
      'Ciências Biológicas',
      'Ciências Contábeis',
      'Design',
      'Direito',
      'Educação Especial',
      'Educação Física - Bacharelado',
      'Educação Física - Licenciatura',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia da Computação',
      'Engenharia de Alimentos',
      'Engenharia de Produção',
      'Engenharia Elétrica',
      'Engenharia Mecânica',
      'Engenharia Química',
      'Farmácia',
      'Fisioterapia',
      'Fonoaudiologia',
      'Jornalismo',
      'Letras - Inglês',
      'Medicina',
      'Medicina Veterinária',
      'Nutrição',
      'Odontologia',
      'Pedagogia',
      'Psicologia',
      'Publicidade e Propaganda',
      'Sistemas de Informação',
      'Terapia Ocupacional',
      'Zootecnia',
    ],
  },
  {
    id: 'univille',
    name: 'UNIVILLE - Universidade da Região de Joinville',
    courses: [
      'Administração',
      'Arquitetura e Urbanismo',
      'Artes Visuais',
      'Biomedicina',
      'Ciências Biológicas',
      'Ciências Contábeis',
      'Ciências Sociais',
      'Comércio Exterior',
      'Design - Animação',
      'Design - Jogos Digitais',
      'Design - Moda',
      'Design - Produto e Serviço',
      'Design de Interiores',
      'Direito',
      'Economia',
      'Educação Física - Bacharelado',
      'Educação Física - Licenciatura',
      'Enfermagem',
      'Engenharia Ambiental e Sanitária',
      'Engenharia Civil',
      'Engenharia de Produção',
      'Engenharia de Software',
      'Engenharia Elétrica',
      'Engenharia Mecânica',
      'Engenharia Química',
      'Farmácia',
      'Fotografia',
      'Gastronomia',
      'História',
      'Letras',
      'Matemática',
      'Medicina',
      'Odontologia',
      'Pedagogia',
      'Psicologia',
      'Publicidade e Propaganda',
      'Sistemas de Informação',
    ],
  },
  {
    id: 'unc',
    name: 'UnC - Universidade do Contestado',
    courses: [
      'Administração',
      'Agronomia',
      'Biomedicina',
      'Ciências Contábeis',
      'Direito',
      'Educação Física',
      'Enfermagem',
      'Engenharia Ambiental e Sanitária',
      'Engenharia Civil',
      'Engenharia de Software',
      'Farmácia',
      'Fisioterapia',
      'Medicina',
      'Medicina Veterinária',
      'Odontologia',
      'Pedagogia',
      'Psicologia',
    ],
  },
  {
    id: 'unochapeco',
    name: 'Unochapecó - Universidade Comunitária da Região de Chapecó',
    courses: [
      'Administração',
      'Agronomia',
      'Arquitetura e Urbanismo',
      'Biomedicina',
      'Ciência da Computação',
      'Ciências Biológicas',
      'Ciências Contábeis',
      'Ciências Econômicas',
      'Cinema e Mídias Sociais',
      'Design',
      'Design de Moda',
      'Direito',
      'Educação Física - Bacharelado',
      'Educação Física - Licenciatura',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia de Alimentos',
      'Engenharia de Produção',
      'Engenharia Elétrica',
      'Engenharia Mecânica',
      'Engenharia Química',
      'Farmácia',
      'Fisioterapia',
      'Fonoaudiologia',
      'Gastronomia',
      'Inteligência Artificial Aplicada',
      'Jornalismo',
      'Letras - Inglês',
      'Medicina',
      'Medicina Veterinária',
      'Nutrição',
      'Odontologia',
      'Pedagogia',
      'Psicologia',
      'Publicidade e Propaganda',
      'Relações Internacionais',
      'Serviço Social',
    ],
  },
  {
    id: 'unidavi',
    name: 'UNIDAVI - Centro Universitário para o Desenvolvimento do Alto Vale do Itajaí',
    courses: [
      'Administração',
      'Agronomia',
      'Arquitetura e Urbanismo',
      'Biomedicina',
      'Ciências Contábeis',
      'Ciências Econômicas',
      'Direito',
      'Educação Física - Bacharelado',
      'Educação Física - Licenciatura',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia de Produção',
      'Engenharia Mecânica',
      'Farmácia',
      'Fisioterapia',
      'Fonoaudiologia',
      'Medicina',
      'Medicina Veterinária',
      'Mídias Sociais Digitais',
      'Nutrição',
      'Pedagogia',
      'Produção Multimídia',
      'Psicologia',
      'Sistemas de Informação',
    ],
  },
  {
    id: 'uniplac',
    name: 'UNIPLAC - Universidade do Planalto Catarinense',
    courses: [
      'Administração',
      'Arquitetura e Urbanismo',
      'Biomedicina',
      'Ciências Contábeis',
      'Design de Interiores',
      'Direito',
      'Educação Física - Bacharelado',
      'Educação Física - Licenciatura',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia de Produção',
      'Engenharia Elétrica',
      'Engenharia Mecânica',
      'Fisioterapia',
      'Fonoaudiologia',
      'Jornalismo',
      'Letras - Português e Inglês',
      'Matemática',
      'Medicina',
      'Música',
      'Odontologia',
      'Pedagogia',
      'Psicologia',
      'Serviço Social',
      'Sistemas de Informação',
    ],
  },
  {
    id: 'uniarp',
    name: 'UNIARP - Universidade Alto Vale do Rio do Peixe',
    courses: [
      'Administração',
      'Agronomia',
      'Arquitetura e Urbanismo',
      'Biomedicina',
      'Direito',
      'Educação Física - Bacharelado',
      'Educação Física - Licenciatura',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia de Controle e Automação',
      'Engenharia Elétrica',
      'Engenharia Mecânica',
      'Letras - Português e Inglês',
      'Medicina',
      'Medicina Veterinária',
      'Nutrição',
      'Pedagogia',
      'Psicologia',
      'Sistemas de Informação',
    ],
  },
  {
    id: 'unifebe',
    name: 'UNIFEBE - Centro Universitário de Brusque',
    courses: [
      'Administração',
      'Arquitetura e Urbanismo',
      'Ciências Contábeis',
      'Design de Moda',
      'Design Gráfico',
      'Direito',
      'Educação Física - Bacharelado',
      'Educação Física - Licenciatura',
      'Engenharia Civil',
      'Engenharia de Produção',
      'Engenharia Mecânica',
      'Engenharia Química',
      'Medicina',
      'Pedagogia',
      'Produção Têxtil',
      'Psicologia',
      'Publicidade e Propaganda',
      'Sistemas de Informação',
    ],
  },
  {
    id: 'unibave',
    name: 'UNIBAVE - Centro Universitário Barriga Verde',
    courses: [
      'Administração',
      'Agronomia',
      'Biomedicina',
      'Ciências Contábeis',
      'Design de Interiores',
      'Direito',
      'Educação Física - Bacharelado',
      'Educação Física - Licenciatura',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia de Produção',
      'Engenharia de Software',
      'Engenharia Mecânica',
      'Farmácia',
      'Fisioterapia',
      'Medicina Veterinária',
      'Pedagogia',
      'Psicologia',
      'Sistemas de Informação',
    ],
  },
  {
    id: 'unisatc',
    name: 'UNISATC - Centro Universitário SATC',
    courses: [
      'Administração',
      'Design',
      'Engenharia de Computação',
      'Engenharia de Minas',
      'Engenharia de Software',
      'Engenharia Elétrica',
      'Engenharia Mecânica',
      'Engenharia Mecatrônica',
      'Engenharia Química',
      'Jornalismo',
      'Pedagogia',
      'Psicologia',
      'Publicidade e Propaganda',
    ],
  },
  {
    id: 'catolica_sc',
    name: 'Católica de Santa Catarina - Centro Universitário',
    courses: [
      'Administração',
      'Arquitetura e Urbanismo',
      'Biomedicina',
      'Ciências Contábeis',
      'Design',
      'Direito',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia de Produção',
      'Engenharia de Software',
      'Engenharia Elétrica',
      'Engenharia Mecânica',
      'Fisioterapia',
      'Nutrição',
      'Pedagogia',
      'Psicologia',
      'Serviço Social',
      'Teologia',
    ],
  },
  {
    id: 'ielusc',
    name: 'IELUSC - Faculdade IELUSC',
    courses: [
      'Administração',
      'Direito',
      'Educação Física - Bacharelado',
      'Educação Física - Licenciatura',
      'Enfermagem',
      'Fonoaudiologia',
      'Jornalismo',
      'Nutrição',
      'Psicologia',
      'Publicidade e Propaganda',
      'Sistemas para Internet',
    ],
  },
];
