import { University } from '@/types';

export const UNIVERSITIES: University[] = [
  {
    id: 'univali',
    name: 'UNIVALI - Universidade do Vale do Itajaí',
    courses: [
      'Administração',
      'Arquitetura e Urbanismo',
      'Biomedicina',
      'Ciência da Computação',
      'Ciências Biológicas',
      'Ciências Contábeis',
      'Comércio Exterior',
      'Design',
      'Direito',
      'Educação Física',
      'Enfermagem',
      'Engenharia Ambiental',
      'Engenharia Civil',
      'Engenharia de Computação',
      'Engenharia de Produção',
      'Farmácia',
      'Fisioterapia',
      'Fonoaudiologia',
      'Gastronomia',
      'Geografia',
      'História',
      'Logística',
      'Medicina',
      'Nutrição',
      'Oceanografia',
      'Odontologia',
      'Pedagogia',
      'Psicologia',
      'Relações Internacionais',
    ],
  },
  {
    id: 'furb',
    name: 'FURB - Universidade Regional de Blumenau',
    courses: [
      'Administração',
      'Arquitetura e Urbanismo',
      'Artes Visuais',
      'Ciência da Computação',
      'Ciências Biológicas',
      'Ciências Contábeis',
      'Ciências Econômicas',
      'Ciências Sociais',
      'Design',
      'Direito',
      'Educação Física',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia de Produção',
      'Engenharia Elétrica',
      'Engenharia Florestal',
      'Engenharia Mecânica',
      'Engenharia Química',
      'Engenharia de Telecomunicações',
      'Farmácia',
      'Filosofia',
      'Física',
      'Fisioterapia',
      'História',
      'Letras',
      'Matemática',
      'Medicina',
      'Música',
      'Odontologia',
      'Pedagogia',
      'Psicologia',
      'Química',
      'Serviço Social',
      'Sistemas de Informação',
    ],
  },
  {
    id: 'unesc',
    name: 'UNESC - Universidade do Extremo Sul Catarinense',
    courses: [
      'Administração',
      'Artes Visuais',
      'Biomedicina',
      'Ciência da Computação',
      'Ciências Biológicas',
      'Ciências Contábeis',
      'Ciências Econômicas',
      'Direito',
      'Educação Física',
      'Enfermagem',
      'Engenharia Ambiental e Sanitária',
      'Engenharia Civil',
      'Engenharia de Materiais',
      'Engenharia de Produção',
      'Engenharia Mecânica',
      'Engenharia Química',
      'Farmácia',
      'Fisioterapia',
      'Geografia',
      'História',
      'Letras',
      'Matemática',
      'Medicina',
      'Nutrição',
      'Odontologia',
      'Pedagogia',
      'Psicologia',
      'Tecnologia da Informação',
    ],
  },
  {
    id: 'unoesc',
    name: 'UNOESC - Universidade do Oeste de Santa Catarina',
    courses: [
      'Administração',
      'Agronomia',
      'Arquitetura e Urbanismo',
      'Ciência da Computação',
      'Ciências Biológicas',
      'Ciências Contábeis',
      'Direito',
      'Educação Física',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia de Produção',
      'Engenharia Mecânica',
      'Engenharia Química',
      'Farmácia',
      'Fisioterapia',
      'História',
      'Letras',
      'Matemática',
      'Medicina',
      'Medicina Veterinária',
      'Nutrição',
      'Pedagogia',
      'Psicologia',
      'Sistemas de Informação',
    ],
  },
  {
    id: 'univille',
    name: 'UNIVILLE - Universidade da Região de Joinville',
    courses: [
      'Administração',
      'Arquitetura e Urbanismo',
      'Artes Visuais',
      'Ciência da Computação',
      'Ciências Biológicas',
      'Ciências Contábeis',
      'Design',
      'Direito',
      'Educação Física',
      'Enfermagem',
      'Engenharia Ambiental e Sanitária',
      'Engenharia Civil',
      'Engenharia de Software',
      'Engenharia Mecânica',
      'Engenharia de Produção',
      'Farmácia',
      'Fisioterapia',
      'História',
      'Letras',
      'Matemática',
      'Medicina',
      'Medicina Veterinária',
      'Nutrição',
      'Odontologia',
      'Pedagogia',
      'Psicologia',
    ],
  },
  {
    id: 'unc',
    name: 'UnC - Universidade do Contestado',
    courses: [
      'Administração',
      'Agronomia',
      'Arquitetura e Urbanismo',
      'Ciências Biológicas',
      'Ciências Contábeis',
      'Design',
      'Direito',
      'Educação Física',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia de Produção',
      'Engenharia Mecânica',
      'Farmácia',
      'Fisioterapia',
      'História',
      'Letras',
      'Matemática',
      'Medicina Veterinária',
      'Nutrição',
      'Pedagogia',
      'Psicologia',
      'Sistemas de Informação',
    ],
  },
  {
    id: 'unochapeco',
    name: 'Unochapecó - Universidade Comunitária da Região de Chapecó',
    courses: [
      'Administração',
      'Agronomia',
      'Arquitetura e Urbanismo',
      'Ciência da Computação',
      'Ciências Biológicas',
      'Ciências Contábeis',
      'Direito',
      'Educação Física',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia de Alimentos',
      'Engenharia de Produção Mecânica',
      'Engenharia Elétrica',
      'Engenharia Mecânica',
      'Engenharia Química',
      'Farmácia',
      'Fisioterapia',
      'História',
      'Letras',
      'Matemática',
      'Medicina',
      'Medicina Veterinária',
      'Nutrição',
      'Pedagogia',
      'Psicologia',
      'Serviço Social',
    ],
  },
  {
    id: 'unidavi',
    name: 'UNIDAVI - Centro Universitário para o Desenvolvimento do Alto Vale do Itajaí',
    courses: [
      'Administração',
      'Agronomia',
      'Ciências Contábeis',
      'Direito',
      'Educação Física',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia de Produção',
      'Engenharia Mecânica',
      'Farmácia',
      'Fisioterapia',
      'Medicina Veterinária',
      'Nutrição',
      'Pedagogia',
      'Psicologia',
      'Sistemas de Informação',
    ],
  },
  {
    id: 'uniplac',
    name: 'UNIPLAC - Universidade do Planalto Catarinense',
    courses: [
      'Administração',
      'Ciências Biológicas',
      'Ciências Contábeis',
      'Direito',
      'Educação Física',
      'Enfermagem',
      'Engenharia Civil',
      'Farmácia',
      'Fisioterapia',
      'História',
      'Letras',
      'Matemática',
      'Medicina',
      'Nutrição',
      'Odontologia',
      'Pedagogia',
      'Psicologia',
      'Sistemas de Informação',
    ],
  },
  {
    id: 'uniarp',
    name: 'UNIARP - Universidade Alto Vale do Rio do Peixe',
    courses: [
      'Administração',
      'Agronomia',
      'Ciências Biológicas',
      'Ciências Contábeis',
      'Direito',
      'Educação Física',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia de Produção',
      'Engenharia Mecânica',
      'Farmácia',
      'Fisioterapia',
      'Medicina',
      'Medicina Veterinária',
      'Nutrição',
      'Pedagogia',
      'Psicologia',
      'Sistemas de Informação',
    ],
  },
  {
    id: 'unifebe',
    name: 'UNIFEBE - Centro Universitário de Brusque',
    courses: [
      'Administração',
      'Arquitetura e Urbanismo',
      'Ciências Contábeis',
      'Design',
      'Direito',
      'Educação Física',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia de Produção',
      'Engenharia Mecânica',
      'Fisioterapia',
      'História',
      'Letras',
      'Pedagogia',
      'Psicologia',
      'Publicidade e Propaganda',
      'Sistemas de Informação',
    ],
  },
  {
    id: 'unibave',
    name: 'UNIBAVE - Centro Universitário Barriga Verde',
    courses: [
      'Administração',
      'Agronomia',
      'Ciências Contábeis',
      'Direito',
      'Educação Física',
      'Enfermagem',
      'Engenharia Ambiental',
      'Engenharia Civil',
      'Fisioterapia',
      'Medicina Veterinária',
      'Nutrição',
      'Pedagogia',
      'Psicologia',
      'Sistemas de Informação',
    ],
  },
  {
    id: 'unisatc',
    name: 'UNISATC - Centro Universitário SATC',
    courses: [
      'Administração',
      'Ciência da Computação',
      'Design',
      'Direito',
      'Engenharia Civil',
      'Engenharia de Minas',
      'Engenharia de Produção',
      'Engenharia de Software',
      'Engenharia Elétrica',
      'Engenharia Mecânica',
      'Engenharia Mecatrônica',
      'Engenharia Química',
      'Jornalismo',
      'Publicidade e Propaganda',
    ],
  },
  {
    id: 'catolica_sc',
    name: 'Católica de Santa Catarina - Centro Universitário',
    courses: [
      'Administração',
      'Biomedicina',
      'Ciências Contábeis',
      'Direito',
      'Enfermagem',
      'Engenharia Civil',
      'Engenharia de Produção',
      'Engenharia de Software',
      'Farmácia',
      'Fisioterapia',
      'Nutrição',
      'Pedagogia',
      'Psicologia',
      'Publicidade e Propaganda',
      'Sistemas de Informação',
    ],
  },
  {
    id: 'ielusc',
    name: 'IELUSC - Faculdade IELUSC',
    courses: [
      'Administração',
      'Ciências Contábeis',
      'Design de Moda',
      'Direito',
      'Educação Física',
      'Enfermagem',
      'Jornalismo',
      'Letras',
      'Pedagogia',
      'Psicologia',
      'Publicidade e Propaganda',
    ],
  },
];
